name: Site CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "site/**"

  pull_request:
    branches:
      - ma
    paths:
      - "site/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Site
        run: pnpm --filter site exec biome ci .

      - name: Type Check
        run: pnpm --filter site exec tsc --noEmit

      - name: Build Site
        run: pnpm --filter site build

      - name: Run Tests
        run: pnpm --filter site test --if-present